# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build-job:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5.2
      - image: circleci/postgres:9.6.3
        environment:
          POSTGRES_USER: ubuntu

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
  deploy-job:
    docker:
        # specify the version here
      - image: circleci/elixir:1.5.2
      - image: circleci/postgres:9.6.3
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "0c:86:e7:57:a3:da:0f:56:df:5d:3c:a9:f4:39:78:b6"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run --app $HEROKU_APP_NAME "POOL_SIZE=2 mix ecto.migrate -r BeingRashional.Repo"
            heroku restart --app $HEROKU_APP_NAME
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master